name:                aoc2021
version:             0.1.0.0
github:              "mgreen89/aoc2021-haskell"
license:             BSD3
author:              "Matthew Green"
maintainer:          "mgreen89@gmail.com"
copyright:           "2021 Matthew Green"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgreen89/aoc2020-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- advent-of-code-api >= 0.2.8
- aeson
- ansi-terminal
- bytestring
- containers
- criterion
- data-default-class
- deepseq
- directory
- filepath
- lens
- linear
- megaparsec >= 8.0
- monad-loops
- mtl
- nonempty-containers
- pandoc
- parsec
- parser-combinators
- primitive
- split
- text
- time
- unordered-containers
- vector
- yaml

library:
  source-dirs: src

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - PatternGuards
  - RecordWildCards
  - TupleSections
  - TypeApplications
  - ViewPatterns

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - optparse-applicative

tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021

benchmarks:
  aoc2021-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2021
